version: '3'
services:
  splunk:
    image: splunk/splunk
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme